### ISSUE TITLE
gorm:gen 命令生成的 DAO 文件未处理 Annotation Syntax

### ISSUE THREAD

**Issue by Try1Xia** [czx-lab/skeleton#3]
![image](https://github.com/user-attachments/assets/e66a7782-1d95-4c00-89f1-24db4b9a61de)
# gorm:gen 命令生成的 DAO 文件未处理 Annotation Syntax

**问题描述**：
在使用 gorm:gen 命令生成的 DAO 文件中，发现对于 Annotation Syntax 没有进行处理。即使是针对默认的 user 表，这种情况依然存在。

**期望**：
希望能够了解原因

**Comment by czx-lab** [comment]
@Try1Xia 该问题已解决[https://github.com/czx-lab/skeleton/commit/f907a1b43229f5e13b312e7f3926ca92b6ed805c](https://github.com/czx-lab/skeleton/commit/f907a1b43229f5e13b312e7f3926ca92b6ed805c)

**Comment by Try1Xia** [comment]
感谢!
